var annotated_dup =
[
    [ "ActivePath", "struct_active_path.html", "struct_active_path" ],
    [ "AddNodeCommand", "class_add_node_command.html", "class_add_node_command" ],
    [ "ConnectCommand", "class_connect_command.html", "class_connect_command" ],
    [ "DashboardObserver", "class_dashboard_observer.html", "class_dashboard_observer" ],
    [ "DeleteNodeCommand", "class_delete_node_command.html", "class_delete_node_command" ],
    [ "DisconnectCommand", "class_disconnect_command.html", "class_disconnect_command" ],
    [ "FirewallDecorator", "class_firewall_decorator.html", "class_firewall_decorator" ],
    [ "HistoryManager", "class_history_manager.html", "class_history_manager" ],
    [ "ICommand", "class_i_command.html", "class_i_command" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "NetworkBuilder", "class_network_builder.html", "class_network_builder" ],
    [ "NetworkNode", "class_network_node.html", "class_network_node" ],
    [ "NodeDecorator", "class_node_decorator.html", "class_node_decorator" ],
    [ "NodeIterator", "class_node_iterator.html", "class_node_iterator" ],
    [ "NodeState", "class_node_state.html", "class_node_state" ],
    [ "OfflineState", "class_offline_state.html", "class_offline_state" ],
    [ "OnlineState", "class_online_state.html", "class_online_state" ],
    [ "RandomPathStrategy", "class_random_path_strategy.html", "class_random_path_strategy" ],
    [ "ReportFacade", "class_report_facade.html", "class_report_facade" ],
    [ "RoutingStrategy", "class_routing_strategy.html", "class_routing_strategy" ],
    [ "ServerNode", "class_server_node.html", "class_server_node" ],
    [ "ShortestPathStrategy", "class_shortest_path_strategy.html", "class_shortest_path_strategy" ],
    [ "SimulationManager", "class_simulation_manager.html", "class_simulation_manager" ],
    [ "SimulationMemento", "class_simulation_memento.html", "class_simulation_memento" ],
    [ "SimulationObserver", "class_simulation_observer.html", "class_simulation_observer" ],
    [ "StarTopology", "class_star_topology.html", "class_star_topology" ],
    [ "Subnet", "class_subnet.html", "class_subnet" ],
    [ "SubnetIterator", "class_subnet_iterator.html", "class_subnet_iterator" ],
    [ "ToggleStateCommand", "class_toggle_state_command.html", "class_toggle_state_command" ],
    [ "TopologyPrototype", "class_topology_prototype.html", "class_topology_prototype" ],
    [ "VisualEdge", "class_visual_edge.html", "class_visual_edge" ],
    [ "VisualNode", "class_visual_node.html", "class_visual_node" ]
];